# Generated by Django 3.0.5 on 2020-04-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200420_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.Topic'),
        ),
    ]
